### ISSUE TITLE
Filtering Issue

### ISSUE THREAD

**Issue by nelson-ong-97** [ringcentral/nestjs-json-api#12]
Hi the authors, firstly thanks for your contribution for this good lib to intergrate the nestjs application.
After following the filter way from the json-api original docs, I get into the trouble that I couldn't filter it.
Thanks in advance, really appreciate if you guys support me in this case.

I also tried with some another case like:
?filter[id]=4
?filter[id][eq]=4

it shows the same results

![image](https://user-images.githubusercontent.com/61964358/136215670-ab3b20f4-de36-4fe3-94cc-44847ac16f68.png)
![image](https://user-images.githubusercontent.com/61964358/136215823-ed498ee0-c0a1-4cc6-b72f-01178c5035c6.png)

**Comment by klerick** [comment]
Hello @Lies97, thank you for reaching out, I hope that you'll find this lib useful!
Regarding your issue, could you please provide "typeorm" entity for "post-category" so that I can troubleshoot/debug this? The issue is really weird.

**Comment by Lies97** [comment]
1. Yes, I have the same errors when I filter the attributes of the Posts only also.
2. No.

so because I don't really know the fork of github so I created the Repo as public so you can view it. Thanks alot 

https://github.com/Lies97/clone-repo
