### ISSUE TITLE
Authorization Question & Extending Controllers

### ISSUE THREAD

**Issue by arcticShadow** [ringcentral/nestjs-json-api#33]
I'm evaluating options for JSON API in nestJS  - and i'm trying to understand more about how this module works. 

Is it possible to add metadata to Individual routes? I have a decorator that adds  'scopes' metadata to the method (or controller) 

Additionally - 
Some (not all) of my models will have complex requirements. Namely - not all the data will be populated from a DB Some i want to pull from an internal API and merge in. Is there a way i can extend on a method by method basis - without loosing all the existing transformation work?

Thanks

**Comment by klerick** [comment]
You can modification response or request using Interceptors.
All controller with decorator JsonApi has implementation 'JsonApiController' interface.
So you can override default behavior.  

ex:
```
@JsonApi(Addresses, {
  allowMethod: ['getAll', 'getOne', 'patchOne'],
})
export class AddressesController implements JsonApiController {
 public constructor(protected someService: SomeService) {}
  @InjectService() protected service: JsonApiService;

  @UseInterceptors(AddressesInterceptors)
  public async patchOne(
    id: number,
    body: RequestResourceData,
  ): Promise<ResponseResourceObject> {
    if (!this.someService.check()) {
       throw new Error();
    }
    const responseJsonApi = await this.service.patchOne({ route: { id }, body });
    responseJsonApi.meta = {}
  }
}
```

**Comment by arcticShadow** [comment]
Ahhhh thanks that's the piece I was missing - overriding the methods in the controller.

I might not have it quite right yet because I needed to tag the method with @Get/@Post etc to get the methods to be recognised. (But your example, and now I know what to look for, the example controller in your repo, do not have tagged overrides)

I will keep trying next week. 


Thanks so much for an amazing community contribution!

**Comment by klerick** [comment]
The method of controller does not have key word of override, because controller only implements interface JsonApiController. It does not extend. Controller class creates dynamically using config of decorator)

The decorator @Get or @Post does not need, because I tried to implement JSON API specification and all methods are strongly defined there.

feel free to contact me if needed)

**Comment by arcticShadow** [comment]
I have made some progress!

I have created a small repo that shows an issue. I have found that i can work around the issue - by adding `@Get` 

In my controller, I must specify `@Get`on the method,  or I get an error - from Swagger. I think the error is suggesting missing metadata - the meta data is being added when I decorate with method with `@Get` I am still new to Nest, and I am learning some concepts so i don't know if it is a bad idea to add this decorator here.  

See my method here: https://github.com/arcticShadow/nest-jsonapi-example/blob/master/src/account/account.controller.ts#L16

(Note - you can run this repo - start it with `docker compose up` to get databases going properly
