### ISSUE TITLE
Expose Transformer via Service

### ISSUE THREAD

**Issue by arcticShadow** [ringcentral/nestjs-json-api#34]
Hello again. 

I have been looking at ways that we can extend the functionality, without recreating a lot of your existing work. 

I have a requirement, to expose a json api publicly, that does not map to a relational database. I will call a rest api to obtain the data that i need to expose. 

My Current thinking, is that i can define an Entity in typeorm, and pass it to this module. That will dynamically create the JSON Api schema. However, I will need to create the data - by default it will pass to the service, and expect to be able to call a database. I wish to override the method(s) in the controller, and call my internal rest api instead. Then, i can create Entities on the fly. but i need to transform them into json API. 

I have made a small change to your Service, to expose a single transformer method - the change can be seen here: https://github.com/arcticShadow/nestjs-json-api/blob/master/libs/json-api/src/lib/mixins/service/service.mixin.ts#L799 Would you consider including this in your module?

**Comment by arcticShadow** [comment]
Another option that would probably be better for everyone, would be to change the declaration to public on the injected transformer https://github.com/ringcentral/nestjs-json-api/blob/master/libs/json-api/src/lib/mixins/service/service.mixin.ts#L30

Then we can use all the transformer methods from our controller.

**Comment by klerick** [comment]
We do not have open api for transformation service. because these services create dynamically. For this it needs connection of typeorm. The sense of our solution - it works with typeorm and creates crud system on real database easily. if this doesn't fit your needs, it's worth to check other solutions
