### ISSUE TITLE
URL filter parameters on doc not descriptive

### ISSUE THREAD

**Issue by alifey** [ringcentral/nestjs-json-api#48]
Hi, on API docs get filter parameters look like this;

`Example: filter[field]=[object Object]&filter[relation.field]=[object Object]`.

I can't understand how to use different filter operands,
also looked at the types and sources in case the html was misinterpreted, but I couldn't find it.

This works but default  operand is 'eq';

`/user?filter[email]=example@mail.com`

params log;

`{
  include: [],
  filter: { email: { eq: 'example@mail.com' } },
  sort: {},
  page: { number: 1, size: 20 }
}`

**Comment by alifey** [comment]
Sorry also glad i tried it again just reading the very similar closed issue, somehow the problem was solved while i tried to undo the fix there. The project still works interestingly even though I restored it. Sorry again, you can close this issue if possible. May I ask an eta of the new version?

**Comment by klerick** [comment]
@alifey I hope to release new version next week

**Comment by alifey** [comment]
@klerick thanks for the answers and good works, have a good day
